# Generated by Django 2.2.6 on 2019-10-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_authors', models.TextField()),
                ('book_desc', models.TextField(null=True)),
                ('book_edition', models.CharField(max_length=200, null=True)),
                ('book_format', models.CharField(max_length=200, null=True)),
                ('book_isbn', models.CharField(max_length=200, null=True)),
                ('book_pages', models.CharField(max_length=200, null=True)),
                ('book_rating', models.FloatField()),
                ('book_rating_count', models.IntegerField()),
                ('book_review_count', models.IntegerField()),
                ('book_title', models.CharField(max_length=200)),
                ('genres', models.TextField(null=True)),
                ('image_url', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
